### ISSUE TITLE
Promising work

### ISSUE THREAD

**Issue by githubnavigator** [shymega/hurdle#1]
I just wanted to post and say that I'm really looking forward to seeing what happens with this project. Will you be leveraging the Barrier code in this Hurdle (e.g., building on barrier-rs)? Excited to see this development.

**Comment by shymega** [comment]
Thank you. barrier-rs was also my project which I archived after little activity. It was merely an experiment, and did not make it very far; thus there is not much code to leverage. Unfortunately, Hurdle will _not_ be a drop-in replacement for Barrier/Synergy 1.x. The same concept with Barrier and Synergy 1.x remains the safe, except this approach is designed to be far more versatile and easier to extend.

Thank you again for your kind words :+1:
